name: Terraform Plan

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # Adjust when clicking the "Run workflow" button in GitHub Actions portal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ vars.AWS_EU_CENTRAL_1_REGION }}

      - name: Terraform Init
        run: terraform init -backend=true
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: terraform
           