name: Terraform Deploy

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      action:
        description: "Terraform action (apply/destroy)"
        required: true
        default: "apply"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ vars.AWS_EU_CENTRAL_1_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: terraform

      - name: Run Terraform Action
        run: terraform ${{ github.event.inputs.action }} -no-color -auto-approve
        working-directory: terraform

      # - name: Upload Terraform State # so the destroy workflow can use them.
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: terraform-state
      #     path: terraform.tfstate